[workspace]
members = [
    "lgba",
    "lgba_macros",
    "lgba_phf",
    "lgba_romtool",
]
resolver = "2"

[profile.dev]
opt-level = 2
debug = 1
lto = false

[profile.release]
opt-level = 3
debug = 1
lto = true
