[package]
name = "lgba_phf"
version = "0.1.0"
authors = ["Alissa Rao <lymia@lymiahugs.com>"]
edition = "2021"

description = "A PHF library optimized specifically for the GBA."

documentation = "https://docs.rs/lgba_phf/"
repository = "https://github.com/Lymia/lgba"
readme = "../README.md"
include = ["LICENSE", "README.md"]

license = "MIT"

[dependencies]
rayon = ">=1.0"
crossbeam-utils = ">=0.7.2, <0.9"
wyhash = ">=0.3, <=0.5"

[dev-dependencies]
quickcheck = "1.0.2"
bencher = ">=0.1"

[[bench]]
name = "build"
harness = false
