[package]
name = "lgba"
version = "0.1.0"
authors = ["Alissa Rao <lymia@lymiahugs.com>"]
edition = "2021"

description = "A low-level library for creating GBA homebrew and romhacks."

documentation = "https://docs.rs/lgba/"
repository = "https://github.com/Lymia/lgba"
readme = "../README.md"

license = "MIT/Apache-2.0"

[features]
default = ["terminal"]
terminal = []

[dependencies]
num_enum = { version = "0.5.7", default-features = false }

lgba_phf = { version = "0.1.0", path = "../lgba_phf" }
