[[file]]
name = "file_a"
path = "../LICENSE-MIT"

[[dir]]
name = "dir_a"
path = "../lgba_common/examples"

[[dir]]
name = "dir_b"
path = "../lgba_common/examples"
enable_dir_listing = true
enable_file_names = true
