[package]
name = "lgba_scripts_codegen"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1"
bdf = "0.6"
kanji = "2"
unic-ucd = "0.9"

lgba_phf = { version = "*", path = "../lgba_phf", features = ["generator"] }
