[package]
name = "lgba_macros"
version = "0.1.0"
authors = ["Alissa Rao <lymia@lymiahugs.com>"]
edition = "2021"

description = "Not public API!"

documentation = "https://docs.rs/lgba/"
repository = "https://github.com/Lymia/lgba"
readme = "../README.md"

license = "MIT/Apache-2.0"

[lib]
proc-macro = true

[dependencies]
darling = { version = "0.14.1", default-features = false }
syn = "1"
quote = "1"
proc-macro2 = "1"
