[package]
name = "lgba_romtool"
version = "0.1.0"
authors = ["Lymia Kanokawa <lymia@lymia.moe>"]
edition = "2021"

description = "The tool used by lgba to work with the produced ROM files."

documentation = "https://docs.rs/lgba/"
repository = "https://github.com/Lymia/lgba"
readme = "../README.md"

license = "MIT/Apache-2.0"

[features]

[dependencies]
anyhow = "1.0"
byteorder = "1.4"
clap = { version = "4.3", features = ["derive", "color"] }
dirs = "5.0"
goblin = "0.6"
tracing = "0.1"
tracing-subscriber = "0.3"